management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /shopee-users-service
  port: 8000
spring:
   application:
      name: shopee-users-service
   h2:
      console:
      enabled: true
      path: /h2
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:~/Explore/shopee/shopee-users-service/data/shopee_users_service;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      username: sa
      password: sa
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
      hibernate:
         ddl-auto: update
         naming:
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
           physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


secret: a6d9ac5b-779b-44a1-9fef-ba272802

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9000/shopee-naming-server/eureka
   instance.prefer-ip-address: true